set.seed("1234")
suppressMessages(library(argparse))
suppressMessages(library(DESeq2))
suppressMessages(library(readr))
suppressMessages(library(stringr))
suppressMessages(library(ggplot2))
suppressMessages(library(pheatmap))
suppressMessages(library(affy))
suppressMessages(library(RColorBrewer))
suppressMessages(library(genefilter ))
suppressMessages(library(data.table))
library(ggrepel)
library(dplyr)  # Ensure dplyr is loaded for select function
library(viridis) # Load viridis for color palettes
library(ComplexHeatmap)
library(grid)
library(SummarizedExperiment)
library(grDevices)  # For different graphic devices
library(glue)
library(circlize)
library(limma)
library(ellipse)
library(DESeq2)
library(dendextend)
library(EnhancedVolcano)
library(ggsci)
library(tidyr)
library(UpSetR)
library(purrr)
library(yaml)
